---
ID: "9d4372bf-27f6-4d30-98ee-056bb1b69034"
Parent: "9d3f5467-eca7-4aa8-9087-a9bd7e2b8822"
Template: "c6d4ddd5-b912-4c1a-a3a3-e1d90e4d0939"
Path: /sitecore/templates/Robbie/Content/Content/New _ProfilingSettings
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 50
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170413T172645Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
